# Generated by Django 5.2.5 on 2025-08-26 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_user', '0002_remove_device_user_device_hostname_device_ip_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
